person:
  username: å°ä¼˜
# ä¸€èˆ¬ä¸ç”¨å¼•å·    åœ¨ymlä¸­ï¼š å•å¼•å·ä¼šå°†  \n ä½œä¸ºå­—ç¬¦ä¸²è¾“å‡º  åŒå¼•å·ä¼šå°† \n ä½œä¸ºæ¢è¡Œè¾“å‡º
# åœ¨ymlä¸­ï¼ŒåŒå¼•å·ä¸ä¼šè½¬ä¹‰ï¼Œå•å¼•å·ä¼šè½¬ä¹‰
  boss: true
  birth: 2000/10/20
  age: 18

#ç¬¬ä¸€ç§æ•°ç»„è¡¨ç¤ºæ–¹å¼
  interests:
    - æ— æš‡
    - æ‹ç…§

# ç¬¬äºŒç§æ•°ç»„è¡¨ç¤ºæ–¹å¼
  animal: [ğŸ±, ğŸ•, çŒ«çŒ«, ç‹—ç‹—]

  #map ç¬¬ä¸€ç§è¡¨ç¤ºæ–¹å¼
#  score:
#    english: 90
#    math: 88

  #map ç¬¬äºŒç§è¡¨ç¤ºæ–¹å¼
  score: {english: 90, math: 99}
  salarys:
    - 1000.00
    - 99.9

  pet:
    name: çŒ«çŒ«
    weigh: 12.0
  allPets:
    sick:
      - { name: çŒ«ä¸€, weight: 12.0}
      - name: çŒ«äºŒ
        weigh: 11.0
      - name: å…”å­
        weight: 10.2
    health:
      - { name: ç‹ä¸€, weight: 9.0}
      - { name: ç‹äºŒ, weight: 9.0}